### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefine

### ISSUE THREAD

**Issue by thecherrie** [AgoraIO-Community/Agora-Node-TokenServer#3]
Cloned the repository, replaced `APP_ID`, and `APP_CERTIFICATE` with my own. The following error is shown when trying to access the `/access_token` endpoint: `http://localhost:8080/access_token?channelName=testchannel`:

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:330:9)
    at AccessToken.build (/Users/<omitted>/Agora-Node-TokenServer/node_modules/agora-access-token/src/AccessToken.js:31:21)
    at Function.buildTokenWithAccount (/Users/<omitted>/Agora-Node-TokenServer/node_modules/agora-access-token/src/RtcTokenBuilder.js:70:25)
    at Function.buildTokenWithUid (/Users/<omited>/Agora-Node-TokenServer/node_modules/agora-access-token/src/RtcTokenBuilder.js:40:21)
    at generateAccessToken (/Users/<omitted>/Agora-Node-TokenServer/index.js:47:33)
    at Layer.handle [as handle_request] (/Users/<omitted>/Agora-Node-TokenServer/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/<omitted>/Agora-Node-TokenServer/node_modules/express/lib/router/route.js:137:13)
    at nocache (/Users/<omitted>/Agora-Node-TokenServer/index.js:15:3)
    at Layer.handle [as handle_request] (/Users/<omitted>/Agora-Node-TokenServer/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/<omitted>/Agora-Node-TokenServer/node_modules/express/lib/router/route.js:137:13)
```

**Comment by waqadArshad** [comment]
Hi, how did you solve this problem?

**Comment by waqadArshad** [comment]
Sorry to bother you again but where in that do I put my APP_ID and APP SECRET. because this one had a separate file for that.

Thank you.

**Comment by canbalkaya** [comment]
Hi. There are some typos in index.js.

You can find the correct version [here](https://gist.github.com/canbalkaya/4271434125720f80c33b4bffa996891b).

**Comment by EkaanshArora** [comment]
Hi we're sorry this example had some issues before, we've rewritten the server and we hope this should be a much better experience now. Please open a new issue if there's any problem you face, if you tag me I'd be happy to help!
