### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

### ISSUE THREAD

**Issue by waqadArshad** [AgoraIO-Community/Agora-Node-TokenServer#4]
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at AccessToken.build (C:\Users\HP\Desktop\Agora-Node-TokenServer\node_modules\agora-access-token\src\AccessToken.js:31:21)
    at Function.buildTokenWithAccount (C:\Users\HP\Desktop\Agora-Node-TokenServer\node_modules\agora-access-token\src\RtcTokenBuilder.js:70:25)
    at Function.buildTokenWithUid (C:\Users\HP\Desktop\Agora-Node-TokenServer\node_modules\agora-access-token\src\RtcTokenBuilder.js:40:21)
    at generateRTCToken (C:\Users\HP\Desktop\Agora-Node-TokenServer\index.js:59:29)
    at Layer.handle [as handle_request] (C:\Users\HP\Desktop\Agora-Node-TokenServer\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\HP\Desktop\Agora-Node-TokenServer\node_modules\express\lib\router\route.js:137:13)
    at nocache (C:\Users\HP\Desktop\Agora-Node-TokenServer\index.js:15:3)
    at Layer.handle [as handle_request] (C:\Users\HP\Desktop\Agora-Node-TokenServer\node_modules\express\lib\router\layer.js:95:5)
    
    
Picked up your code and ran it after adding my APP ID and APP CERTIFICATE. but this error shows up when I try to use the URLs that you have provided like:  http://localhost:8080/rtc/test/publisher/uid/1
 
Something changed after using this: http://localhost:8080/rtc/:test/:publisher/uid/1
and the out became // 20220212032023
// http://localhost:8080/rtc/:test/:publisher/uid/1

{
  "error": "role is incorrect"
}

even though the role is correct. I even tried audience as the role but the output didn't change. 
and the ping: http://localhost:8080/ping works just fine and produces this output:
// 20220212032146
// http://localhost:8080/ping

{
  "message": "pong"
}

Can you please help me with this? I shall be very thankful.

**Comment by canbalkaya** [comment]
Hi. There are some typos in index.js.

You can find the correct version [here](https://gist.github.com/canbalkaya/4271434125720f80c33b4bffa996891b).

**Comment by Abdelrahman-Nabil** [comment]
> Hi. There are some typos in index.js.
> 
> You can find the correct version [here](https://gist.github.com/canbalkaya/4271434125720f80c33b4bffa996891b).

still not working with the version you provided

**Comment by waqadArshad** [comment]
> > Hi. There are some typos in index.js.
> > You can find the correct version [here](https://gist.github.com/canbalkaya/4271434125720f80c33b4bffa996891b).
> 
> still not working with the version you provided


Hi @Abdelrahman-Nabil, I think you should not bother with this repo. this was problematic and probably would always be. You should go onto this link: 
```
[https://github.com/AgoraIO-Community/agora-token-service](https://github.com/AgoraIO-Community/agora-token-service)

```
But first, make a Heroku account and verify it. Once you have done that, go to the above link and click the "Deploy on Heroku" button. It would ask you to give an app name and then add probably 2 or three environment variables (values of which you would get from your Agora Dashboard). Just do that and press deploy and you'll have your link in a few minutes. Then you can use the guidelines given in the Readme of this linked server to get the token with a normal URL. 
If you need anything, comment here and I'll respond.

**Comment by EkaanshArora** [comment]
Hi we're sorry this example had some issues before, we've rewritten the server and we hope this should be a much better experience now. Please open a new issue if there's any problem you face, if you tag me I'd be happy to help!
